version: '2'
services:
  auto-sklearn:
    build: ./auto-sklearn/docker
    image: auto-sklearn:latest
    volumes:
      - ./auto-sklearn:/home/jovyan/work
      - ./_datasets:/_datasets
    working_dir: /home/jovyan/work
    ports:
      - 8887:8888
    environment: 
      - JUPYTER_ENABLE_LAB=yes

  automl-streams:
    build: ./automl-streams/docker
    image: automl-streams:latest
    volumes:
      - ./automl-streams:/home/jovyan/work
      - ./_datasets:/_datasets
    working_dir: /home/jovyan/work
    ports:
      - 8888:8888
    environment: 
      - JUPYTER_ENABLE_LAB=yes

  h2o:
    build: ./h2o/docker
    image: h2o:latest
    volumes:
      - ./h2o:/home/jovyan/work
      - ./_datasets:/_datasets
    working_dir: /home/jovyan/work
    ports:
      - 8889:8888
    environment: 
      - JUPYTER_ENABLE_LAB=yes
  
  tpot:
    build: ./tpot/docker
    image: tpot:latest
    volumes:
      - ./tpot:/home/jovyan/work
      - ./_datasets:/_datasets
    working_dir: /home/jovyan/work
    ports:
      - 8890:8888
    environment: 
      - JUPYTER_ENABLE_LAB=yes
  
  # Kafka Cluster
  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.1
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  broker:
    image: confluentinc/cp-enterprise-kafka:5.3.1
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,HOST://localhost:9092